### ISSUE TITLE
Potential Syllabus Typos + Readme links

### ISSUE THREAD

**Issue by mistryrohan** [pointOfive/STA130_F23#5]
I am trying to figure out how to create make multiple commits into a single pull request like from the terminal, but when changing a file on GitHub itself it asks me to commit directly to main or create a new branch each time so I will create an issue here for now. 

1. Course email should be changed from STA410@utoronto.ca to STA130@utoronto.ca unless it was intentional
2. Small typo in the latex where a H_0 needs to be turned into a H_A for comparing mu_1 and mu_2 
3. Tutorial T1 and T2 in the readme are the same link (probably is not an issue if week 1 does not have a tutorial)

**Comment by pointOfive** [comment]
It's possible that you'd need to git clone your fork and work locally with git rather than github to have that sort of full control... not a bad work process to consider.
- Check out Matthews pull request (https://github.com/pointOfive/STA130_F23/pull/6), which seems to entail two commits, and see if that's what you're wanting to do:
- If so, check with Matthew to see how he did it and coordinate with Matthew to make a recording of how to do it and share that on slack:
- We should definitely set up general best practices for how we do these sorts of things... especially when you guys have feedback for each other and when I myself am reviewing things

And, great job on the typo checks: thank you!

- ~~sta410@utoronto.ca~~ STA130@utoronto.ca and ~~$H_0$~~ $H_A$ ([commit/7a2e590](https://github.com/pointOfive/STA130_F23/commit/7a2e59092729df9f489081e09647d19d19ec8586))
- Uh Oh! Week 1 has a tutorial! [commit/3e99a84](https://github.com/pointOfive/STA130_F23/commit/3e99a84f0fcb55dcb0a7f8bd452276b0b40bce1d)

Leaving this issue open while we determine if you and Matthew will provide a best practices PSA

**Comment by pointOfive** [comment]
Great video from @mistryrohan -- thanks!
